config/routes.rb
Rails.application.routes.draw do

   root 'welcome#index'

  get '/home' => 'welcome#home', as: :home
  get '/about' => 'welcome#about', as: :about
  get '/contact' => 'welcome#contact', as: :contact
  get '/document' => 'welcome#document', as: :document

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
  end

  def contact
  end

  def document
  end

  def about
    @offset = params[:offset]
    if @offset then
      tumblr_offset = @offset.to_i * 7
    else
      tumblr_offset = 0
      @offset = 0
    end
    @next = @offset.to_i + 1
    @back = @offset.to_i - 1
    client = Tumblr::Client.new
    blog = client.posts("kafcollective.tumblr.com", :limit => 7, :offset => tumblr_offset)
    @posts = blog["posts"]
  end

  def home
    @offset = params[:offset]
    if @offset then
      tumblr_offset = @offset.to_i * 7
    else
      tumblr_offset = 0
      @offset = 0
    end
    @next = @offset.to_i + 1
    @back = @offset.to_i - 1
    client = Tumblr::Client.new
    blog = client.posts("kafcollective.tumblr.com", :limit => 7, :offset => tumblr_offset)
    @posts = blog["posts"]
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Kaf</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
    <%= csrf_meta_tags %>
    <%= favicon_link_tag 'favicon.ico' %>
</head>
<body>
<%= yield %>

</body>
</html>

app/views/shared/_top_nav.html.erb
<div class="top_nav">
KAF READING SERIES
</div>

app/views/welcome/about.html.erb
<div class="top_nav">
KAF COLLECTIVE
</div>
<div class="container">
<div id="navigation">
  <ul class="nav">
    <li><%=link_to "ABOUT", "#about", :class => "about-link"%></li>
   <li><%=link_to "CONTACT", contact_path%></li>
   <li><%=link_to "DOCUMENT", document_path%></li>
  </ul>
  <div class="about" style="display:block">
    <p>
    <span style="font-weight:bold">KAF </span> means "palm" in Arabic, Cuneiform, Farsi, Hebrew, Phoenician, Urdu, and many other languages. Kaf is the letter K in each. It signifies touch, vulnerability, intimacy. The hand lifted before it is clenched.
    </p>
     <p>
  It shares its name with mount Qaf, the fabled goal of the Hoopoe and its followers in the sufi poem "The Conference of the Birds”. It is half of Kafka, the Czech author of empirical impasse, cruel absurdity.

    </p>
     <p>
  Like the Hoopoe and Kafka’s K, we travel by wandering, without preconceived destination.

    </p>
      <p>
  KAF curates work that moves "toward and away from text", work that interacts with body, image & sound, work that places value on the space between words, letters, genres, discourses, languages.

    </p>
     <p>
  KAF is an inquiry into the very possibility of itself. A well as a sustained meditation on the political, geographic and cultural borders that obscure this possibility.
    </p>  
  </div>
</div>
  <table>
    <tr>
  <td valign="top">
    <%if @posts == []%>
       <div class = "body">
       There are no more posts to show
       </div>
    <%end%>
    <%@posts.each do |post|%>
       <div class="post-title">
          <div class="title">
            <%=strip_tags(post["caption"])%>
          </div>
          
          <div class="body">
            <%myphoto = post["photos"]%>
            <%if myphoto.class == Array %>
                <%=image_tag myphoto[0]["alt_sizes"][0]["url"]%>
            <%end%>
            <%=raw post["body"]%>
            <div class="date">
            <%=DateTime.new(post["date"].split(' ').first.split('-').first.to_i, post["date"].split(' ').first.split('-').second.to_i, post["date"].split(' ').first.split('-').third.to_i).strftime("Printed on %m/%d/%Y") %>
            </div>
          </div>
        </div>
    <%end%>
    <div class="next">
      <%if @back >= 0 then%>
      <%= link_to(home_path(:offset => @back)) do %>
      <i class="pe-7s-angle-left pe-3x pe-va"></i>
      <%end%>
      <%end%>
      <%= link_to(home_path(:offset => @next)) do %>
      <i class="pe-7s-angle-right pe-3x pe-va"></i>
      <%end%>
    </div>
  </td>
</div>

app/views/welcome/contact.html.erb
<div class="top_nav">
KAF COLLECTIVE
</div>
<div class="container">
<div id="navigation">
  <ul class="nav">
    <li><%=link_to "ABOUT", "#about", :class => "about-link"%></li>
   <li><%=link_to "CONTACT", contact_path%></li>
   <li><%=link_to "DOCUMENT", document_path%></li>
  </ul>
  <div class="about">
    <p>
    <span style="font-weight:bold">KAF </span> means "palm" in Arabic, Cuneiform, Farsi, Hebrew, Phoenician, Urdu, and many other languages. Kaf is the letter K in each. It signifies touch, vulnerability, intimacy. The hand lifted before it is clenched.
    </p>
     <p>
  It shares its name with mount Qaf, the fabled goal of the Hoopoe and its followers in the sufi poem "The Conference of the Birds”. It is half of Kafka, the Czech author of empirical impasse, cruel absurdity.

    </p>
     <p>
  Like the Hoopoe and Kafka’s K, we travel by wandering, without preconceived destination.

    </p>
      <p>
  KAF curates work that moves "toward and away from text", work that interacts with body, image & sound, work that places value on the space between words, letters, genres, discourses, languages.

    </p>
     <p>
  KAF is an inquiry into the very possibility of itself. A well as a sustained meditation on the political, geographic and cultural borders that obscure this possibility.
    </p>  
  </div>
</div>
  <table>
    <tr>
  <td valign="top">
     tmhaviv (at) gmail (dot) com
    </div>
  </td>
</div>

app/views/welcome/document.html.erb
<div class="top_nav">
KAF COLLECTIVE
</div>
<div class="container">
<div id="navigation">
  <ul class="nav">
    <li><%=link_to "ABOUT", "#about", :class => "about-link"%></li>
   <li><%=link_to "CONTACT", contact_path%></li>
   <li><%=link_to "DOCUMENT", document_path%></li>
  </ul>
  <div class="about">
    <p>
    <span style="font-weight:bold">KAF </span> means "palm" in Arabic, Cuneiform, Farsi, Hebrew, Phoenician, Urdu, and many other languages. Kaf is the letter K in each. It signifies touch, vulnerability, intimacy. The hand lifted before it is clenched.
    </p>
     <p>
  It shares its name with mount Qaf, the fabled goal of the Hoopoe and its followers in the sufi poem "The Conference of the Birds”. It is half of Kafka, the Czech author of empirical impasse, cruel absurdity.

    </p>
     <p>
  Like the Hoopoe and Kafka’s K, we travel by wandering, without preconceived destination.

    </p>
      <p>
  KAF curates work that moves "toward and away from text", work that interacts with body, image & sound, work that places value on the space between words, letters, genres, discourses, languages.

    </p>
     <p>
  KAF is an inquiry into the very possibility of itself. A well as a sustained meditation on the political, geographic and cultural borders that obscure this possibility.
    </p>  
  </div>
</div>
  <table>
    <tr>
  <td valign="top">
     TBD
    </div>
  </td>
</div>

app/views/welcome/home.html.erb
<div class="top_nav">
KAF COLLECTIVE
</div>
<div class="container">
<div id="navigation">
  <ul class="nav">
   <li><%=link_to "ABOUT", "#about", :class => "about-link"%></li>
   <li><%=link_to "CONTACT", contact_path%></li>
   <li><%=link_to "DOCUMENT", document_path%></li>
  </ul>
  <div class="about">
    <p>
    <span style="font-weight:bold">KAF </span> means "palm" in Arabic, Cuneiform, Farsi, Hebrew, Phoenician, Urdu, and many other languages. Kaf is the letter K in each. It signifies touch, vulnerability, intimacy. The hand lifted before it is clenched.
    </p>
     <p>
  It shares its name with mount Qaf, the fabled goal of the Hoopoe and its followers in the sufi poem "The Conference of the Birds”. It is half of Kafka, the Czech author of empirical impasse, cruel absurdity.

    </p>
     <p>
  Like the Hoopoe and Kafka’s K, we travel by wandering, without preconceived destination.

    </p>
      <p>
  KAF curates work that moves "toward and away from text", work that interacts with body, image & sound, work that places value on the space between words, letters, genres, discourses, languages.

    </p>
     <p>
  KAF is an inquiry into the very possibility of itself. A well as a sustained meditation on the political, geographic and cultural borders that obscure this possibility.
    </p>  
  </div>
</div>
  <table>
    <tr>
  <td valign="top">
    <%if @posts == []%>
       <div class = "body">
       There are no more posts to show
       </div>
    <%end%>
    <%@posts.each do |post|%>
       <div class="post-title">
          <div class="title">
            <%=strip_tags(post["caption"])%>
          </div>
          
          <div class="body">
            <%myphoto = post["photos"]%>
            <%if myphoto.class == Array %>
                <%=image_tag myphoto[0]["alt_sizes"][0]["url"]%>
            <%end%>
            <%=raw post["body"]%>
            <div class="date">
            <%=DateTime.new(post["date"].split(' ').first.split('-').first.to_i, post["date"].split(' ').first.split('-').second.to_i, post["date"].split(' ').first.split('-').third.to_i).strftime("Printed on %m/%d/%Y") %>
            </div>
          </div>
        </div>
    <%end%>
    <div class="next">
      <%if @back >= 0 then%>
      <%= link_to(home_path(:offset => @back)) do %>
      <i class="pe-7s-angle-left pe-3x pe-va"></i>
      <%end%>
      <%end%>
      <%= link_to(home_path(:offset => @next)) do %>
      <i class="pe-7s-angle-right pe-3x pe-va"></i>
      <%end%>
    </div>
  </td>
</div>

app/views/welcome/index.html.erb
<div class='gif'>
  <%=link_to(home_path) do %>
    <%=image_tag("kaf_gif.gif")%>
    <%end%>
</div>